spring:
  main:
    banner_mode: 'OFF'
  profiles:
    active: production

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 20

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.H2Dialect
exchange:
  csv:
    url: "https://api.statistiken.bundesbank.de/rest/download/BBEX3/D.{currency}.EUR.BB.AC.000?format=csv&lang=en"
currencies:
  csv:
    url: "https://api.statistiken.bundesbank.de/rest/download/BBEX3/D..EUR.BB.AC.000?detail=full&format=csv&lang=en"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
